[package]
name = "mandlebrot"
version = "0.1.0"
authors = ["Scott Fones <scott.fones@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
image = "0.13.0"
num = "0.4"